name: "Build"

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
        os:
          - linux
          - darwin
          - windows
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build .
